# Generated by Django 3.2.16 on 2023-02-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='text_field',
        ),
        migrations.AddField(
            model_name='customuser',
            name='wish',
            field=models.TextField(blank=True, verbose_name='wish field'),
        ),
    ]
